#!/bin/bash
sed '/app.use(app.router);/i '
 app.use(expressWinston.logger({
      transports: [
        new winston.transports.Console({
          json: true,
          colorize: true
        })
      ]
    })); ' to.txt
