#!/bin/bash
apt-get -y update
apt-get install -y python-software-properties
add-apt-repository -y ppa:ferramroberto/java
add-apt-repository -y ppa:openjdk/ppa
apt-get install -y  openjdk-7-jdk
mkdir /usr/java
ln -s /usr/lib/jvm/java-7-openjdk-amd64 /usr/java/default
